Sprint 8: Имплементировал ТЗ
Alex-Ivash/java-kanban pull request #3
Opened 2024-06-19 20:59 UTC by Alex-Ivash

2024-06-20 13:39 UTC, TomattmanYandex requested changes
Разобью по пунктам

При считывании данных в файловом менеджере, необходимо для эпика посчитать время окончания

Кажется что многие моменты сильно переусложнены, в ущерб читаемости, обычно читаемость и понятность выше по риоритету

Написал много комментариев  в тесте менеджера истории, проверь чтобы они так же выполнялись в других тестах

2024-06-20 13:39 UTC, TomattmanYandex commented on src/converter/TaskConverter.java
> +        return toString((Task) task).replaceFirst("null", String.valueOf(task.getEpicId()));
не лучшее решение, ибо легко сломать задав имя таска или description null

2024-06-20 13:39 UTC, TomattmanYandex commented on src/converter/TaskConverter.java
> +        LocalDateTime startTime = LocalDateTime.parse(taskFields[6]);
Уверен что это сработает без ошибок, если время страта или продолжительность будет null?

2024-06-20 13:39 UTC, TomattmanYandex commented on src/model/Task.java
> +        return startTime.plus(duration);
Что будет если время старта или продолжительность будут равны null?

2024-06-20 13:39 UTC, TomattmanYandex commented on src/model/TaskStatus.java
> +    NEW(0),
я понимаю зачем эти изменения, но с текстовым представлением нагляднее

2024-06-20 13:39 UTC, TomattmanYandex commented on src/model/TaskStatus.java
> +    NEW(0),
хотя нет, не понимаю

2024-06-20 13:39 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        historyManager.add(findTask(task, id));
зачем это? у тебя действием раньше уже есть найденный таск

2024-06-20 13:39 UTC, TomattmanYandex commented on src/model/Task.java
> +    public static final LocalDateTime DEFAULT_START_TIME = LocalDateTime.of(9999, 12, 31, 23, 59, 59);
Если хочешь сделать эти константы, то лучше сделать их в сервисе (таск менеджере)
но зачем они, ведь если у чего то будет стандартное время старта и продолжительность, то они будут пересекаться сами с собой, всегда

2024-06-20 13:39 UTC, TomattmanYandex commented on src/model/Task.java
> +    protected TaskStatus status; // TODO сделать статус NEW дефолтным?
не уверен что имеет смысл делать статус new дефолтным

2024-06-20 13:39 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        if (!newTask.getStartTime().equals(Task.DEFAULT_START_TIME)) {
не понимаю что это и зачем,
если нету времени старта то можно оставить null и по нему проще гораздо понимать, есть оно там или нет

2024-06-20 13:39 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        Epic subtaskEpic = (Epic) findTask(epics.get(newSubtask.getEpicId()), newSubtask.getEpicId());
снова вопрос, зачем эти изменения?

2024-06-20 13:39 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        if (!oldTask.getStartTime().equals(newTask.getStartTime())
но по сути это и есть валидация времени, а она уже выполнена выше в строке 152

2024-06-20 13:39 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        if (!oldSubtask.getStartTime().equals(newSubtask.getStartTime())
аналогично

2024-06-20 13:39 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        if (checkedTask.getStartTime().equals(Task.DEFAULT_START_TIME)) {
про дефолтное значение я уже писал

2024-06-20 13:39 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        Stream.of(prioritizedTasks.floor(checkedTask), prioritizedTasks.ceiling(checkedTask))
Честно, понять очень сложно, и не только сам код но и логику
1) зачем это действие, ведь по сути, ты получаешь стрим из все тех же всех элементов списка
2) условия, тоже тяжеловато понять

рекомендация как сделать
- сделать метод, который проверяет два таска на паресечение (обязательно проверь их на то что это не один и тот же таск, ибо он пересекается сам с собой обычно) и чтобы он возвращал boolean 
- пройтись по приоритезированному списку и отфильтровать методом выше
- если остался хоть один элемент, значит с нем есть пересечение, кидаем ошибку

таким образом будет читаться гораздо понятнее

2024-06-20 13:39 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        validateCollision(newSubtask, oldSubtask);
зачем проверять пересечение старого и нового тасков?
они скорее всего будут иметь пересечение, важно проверить пересечение нового таска с любым из существующих

2024-06-20 13:39 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        List<Subtask> epicsSubtasks = getEpicSubtasks(epic.getId());
теперь этот метод слабо читаемы и понимаемый

2024-06-20 13:39 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        List<Subtask> epicsSubtasks = getEpicSubtasks(epic.getId());
раньше логика была понятна и логична, теперь появились какие то волшебный числа битовые операции и непонятно что

2024-06-20 13:39 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        List<Subtask> epicsSubtasks = getEpicSubtasks(epic.getId());
плюс смесь высчитывания сразу всего в одном методе

2024-06-20 13:39 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        List<Subtask> epicsSubtasks = getEpicSubtasks(epic.getId());
как бы я рекомендовал сделать
есть метод calculateEpicState(Epic epic)
1) получили список сабтасков
2) epic.setStatus(getEpicStatus(subtasks));// getEpicStatus возвращает статус эпика, и лучше как раньше, когда это было легко читаемо и понятно
3) epic.setStartTime(getEpicStartTIme(subtasks));//аналогично
4) epic.setEndTime(getEpicEndTIme(subtasks));//аналогично
5) epic.setDurationTime(getEpicDuration(subtasks));//аналогично

2024-06-20 13:39 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        List<Subtask> epicsSubtasks = getEpicSubtasks(epic.getId());
теперь по поводу высчитывания времени
subtasks.stream()
.map(Subtask::getStratTime)// или getDuration или getEndTime
.filter(Objects::notNull) //чтобы игнорить пустые значения
.sorted(/*по возрастанию*/)//для продолжительности не надо
.findFirst()//для времени окончания findLast для продолжительности - просуммировать

2024-06-20 13:39 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        List<Subtask> epicsSubtasks = getEpicSubtasks(epic.getId());
итого получится 4 приватных метода каждый несет свой небольшой функционал, но понятный, и с хорошим именем метода
 и один который вызывает их по очереди

2024-06-20 13:39 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +    private Task findTask(Task task, int id) {
плохое имя для метода, зачем нам искать его, если он уже есть назвать бы его getNotNullValue

2024-06-20 13:39 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        historyManager.add(findTask(task, id));
дошел до метода понял что он делает, там оставил рекомендацию как его назвать, а тут реализацю, как лучше сделать
Task task = getNotNullValue(tasks.get(id));
historyManager.add(task);
return task;

таким образом у тебя в переменной всегда будет не нулевое значение

2024-06-20 13:39 UTC, TomattmanYandex commented on test/model/EpicTest.java
> +    private static int seq;
видимо в предыдущей итерации плохо посмотрел тесты
так вот
эпик не зависит никак о т таскового менеджера, следовательно, в его тестах не нужен таск менеджер
а если нужен, значит это должно быть в тесте таск менеджера

2024-06-20 13:39 UTC, TomattmanYandex commented on test/model/EpicTest.java
> +        testObjectsContainer = new ArrayList<>();
зачем эта переменная?

2024-06-20 13:39 UTC, TomattmanYandex commented on test/model/EpicTest.java
> +            Subtask subtask = new Subtask(++seq, TaskStatus.NEW, "name", "description", epic.getId(), Task.DEFAULT_START_TIME, Task.DEFAULT_DURATION);
эпик ничего не знает о сабтасках, следовательно, эти вещи тут и не нужны

2024-06-20 13:39 UTC, TomattmanYandex commented on test/model/EpicTest.java
> +            testObjectsContainer.add(subtask);
если тебе нужна переменная для сравнения кон=личества, то лучше создать ее на уровне класса, так меньше шанс на всякие ошибки, например ели переменная не занулится, то будет уже ошибка

2024-06-20 13:39 UTC, TomattmanYandex commented on test/model/EpicTest.java
> +        Subtask subtask = new Subtask(++seq, TaskStatus.NEW, "name", "description", epic.getId(), Task.DEFAULT_START_TIME, Task.DEFAULT_DURATION);
этот тест тоже не имеет смысла, так как эпик не знает ничего о тасковом менеджере и следовательно удалить ничего не может

2024-06-20 13:39 UTC, TomattmanYandex commented on test/model/EpicTest.java
единственный тест который тут должен быть, это тест, что при добавлении эпику в список сабтасков число одинаковое с его идентификатором, оно не должно добавляться
и наоборот, что любое другое число добавляется

2024-06-20 13:39 UTC, TomattmanYandex commented on test/service/managers/history/InMemoryHistoryManagerTest.java
> +    private static ArrayList<Task> testObjectsContainer;
тут то же что и выше менеджер истории ничего не знает и не должен знать от таскового менеджера, следовательно и в тесте таскового менеджера быть не должно

2024-06-20 13:39 UTC, TomattmanYandex commented on test/service/managers/history/InMemoryHistoryManagerTest.java
> +    private static ArrayList<Task> testObjectsContainer;
тут надо проверить только методы менеджера истории
а уже в тесте таскового менеджера следует проверить, что после того как мы запрашиваем таск по идентификатору, в истории он возвращается

2024-06-20 13:39 UTC, TomattmanYandex commented on test/service/managers/history/InMemoryHistoryManagerTest.java
> +    private static final int TASKS_COUNT = 3;
кажется эти переменный тут тоже не нужны

2024-06-20 13:39 UTC, TomattmanYandex commented on test/service/managers/history/InMemoryHistoryManagerTest.java
> +        IntStream.range(0, taskTypes.size()).forEach(i ->
1) это как минимум частично тест таскового менеджера, а не менеджера истории

2024-06-20 13:39 UTC, TomattmanYandex commented on test/service/managers/history/InMemoryHistoryManagerTest.java
> +        IntStream.range(0, taskTypes.size()).forEach(i ->
2) он очень переусложнен
хороший тест(для таск менеджера)
добавили в ручную пару тасков, сабтасков, эпиков (можно по одному) 
вызвали методы get для каждого, 
получили историю
проверили что все для кого мы вызывали get добавились в историю

2024-06-20 13:39 UTC, TomattmanYandex commented on test/service/managers/history/InMemoryHistoryManagerTest.java
> +        List<Integer> taskIds = taskManager.getAllTasks().stream().map(Task::getId).toList();
вот тут хороший тест для менеджера истории, но должен быть без таскового менеджера
1) создаем таск через конструктор
2) добавляем его несколько раз, смотрим что добавился только один

отдельным тестом
1) создаем таск через конструктор
2) добавляем его
3) изменяем его
4) добавляем снова
5) смотрим что в менеджере истории последняя версия

отдельным тестом
1) создаем таск через конструктор
2) добавляем его
3) создаем второй таск через конструктор
4) добавляем второй таск
5) смотрим что в менеджере истории на первой позиции второй таск, на второй позиции первый таск

2024-06-20 13:39 UTC, TomattmanYandex commented on test/service/managers/history/InMemoryHistoryManagerTest.java
> +        int taskId = taskManager.getAllTasks().getFirst().getId();
хороший тест, но без таск менеджера должен быть

2024-06-20 13:39 UTC, TomattmanYandex commented on test/service/managers/history/InMemoryHistoryManagerTest.java
> +        List<Integer> taskIds = switch (taskType) {
это точно тест таск менеджера
и снова переусложенено

2024-06-20 13:39 UTC, TomattmanYandex commented on test/service/managers/history/InMemoryHistoryManagerTest.java
комментарий ко всему тесту
1) тесты переусложнены
обычно в тестах все хардкодят, (в очень хороших тестах есть элементы рандома, но такие делают гораздо реже, потому что обычно они того не стоят)
в текущих же тестах все захардкожено, но очень сложно
2) если ты тестируешь класс который не зависит от другого класса, то это другой класс в тесте и не нужен
таск менджер зависит от менеджера истории, там ссылка на него имеет смысл, тут нет
3) имена методов, у тебя они почти отличные, но можно чуть улучшить 
пример
add_whenViewAgainExistingViewInTheHistoryIsDeleted
add_deleteExisting_addedSame
- имя тестового метода присутствует - прекрасно
- в именах методов мы обычно не используем нижние подчеркивания, и поэтому нижнее подчеркивание в имени тестового метода отлично показывает, разделение на части (можно не писать when и should)
- у нас нету такого процесса как view поэтому лучше написать в тех понятиях которыми мы оперируем
менеджер истории оперирует только добавлением и удалением, (менеджер тасков оперирует получением там можно написать getSame
- лучше разделять что должно случиться и почему
- в начале пишем что должно случиться, а потом при каких условиях, потому что что-то случается всегда, а вот условия не всегда пишем (например при нормальных условиях)

4) по поводу структуры методов
хороший тестовый метод имеет следующую структуру, которую часто выделают комментариями
//given
тут код, подготовки теста, например для того чтобы добавить таск в историю, таск нужно в начале создать, стоит это сделать тут, в тесте таскового менеджера, для того чтобы его получить, его надо сначала создать и добавить в тасковый менеджер, это тоже лучше сделать тут
//that 
вызываем метод который тестируем
//then
а тут уже все проверки

5)количество тестовых методов
обычно тестовый метод создается на каждый конкретный случай
например
add_addTaskToHistory
add_deletePrevious_taskAlreadyExist
или для таскового менеджера
getTaskById_addToHistory
getSubtaskById_addToHistory
getEpicById_addToHistory

так если упадет один маленький тест, есть шанс что не упадут другие, или если уппдут сразу несколько, то легче  будет понять почему они падают

2024-06-20 14:03 UTC, Alex-Ivash commented on src/converter/TaskConverter.java
> +        LocalDateTime startTime = LocalDateTime.parse(taskFields[6]);
Постарался сделать NPE - безопасно в этом моменте, насколько смог, используюя значения по умолчанию, вместо тысячи проверок на null в методах.

2024-06-20 14:04 UTC, Alex-Ivash commented on src/model/Task.java
> +        return startTime.plus(duration);
Выше отписал

2024-06-20 14:05 UTC, Alex-Ivash commented on src/model/TaskStatus.java
> +    NEW(0),
Для быстрого расчета статуса при помощи битового вектора в методе расчета таск менеджера

2024-06-20 14:07 UTC, Alex-Ivash commented on src/model/Task.java
> +    public static final LocalDateTime DEFAULT_START_TIME = LocalDateTime.of(9999, 12, 31, 23, 59, 59);
По поводу пересечения с самим собой при дефолтном времени старта учел.
Дефолтная продолжительность нулевая, так что пересечений быть не должно.

2024-06-20 14:08 UTC, Alex-Ivash commented on src/model/Task.java
> +    protected TaskStatus status; // TODO сделать статус NEW дефолтным?
Если при создании статус не указали, то, вроде, логично, что он NEW

2024-06-20 14:15 UTC, Alex-Ivash commented on src/service/managers/task/InMemoryTaskManager.java
> +        if (!newTask.getStartTime().equals(Task.DEFAULT_START_TIME)) {
Проще, но ведь опаснее и порождает кучу доп. проверок.
Удобнее влепить не так много таких проверок только в нужные места и не получать NPE в неожиданных кейсах

2024-06-20 14:19 UTC, Alex-Ivash commented on src/service/managers/task/InMemoryTaskManager.java
> +        Epic subtaskEpic = (Epic) findTask(epics.get(newSubtask.getEpicId()), newSubtask.getEpicId());
Это проверка на существование эпика создаваемого сабтаска.
Хотя, мы же считаем де-факто, что аргументы везде будут "правильными", тогда уберу.

2024-06-20 14:30 UTC, Alex-Ivash commented on src/service/managers/task/InMemoryTaskManager.java
> +        if (!oldTask.getStartTime().equals(newTask.getStartTime())
Да, но я хотел лишний раз не перевставлять таски в список по приоритетам. Но выглядит избыточно - поправил.

2024-06-20 14:31 UTC, Alex-Ivash commented on src/service/managers/task/InMemoryTaskManager.java
> +        if (!oldSubtask.getStartTime().equals(newSubtask.getStartTime())
Поправил

2024-06-20 14:34 UTC, Alex-Ivash commented on src/service/managers/task/InMemoryTaskManager.java
> +        if (checkedTask.getStartTime().equals(Task.DEFAULT_START_TIME)) {
Это чтобы не пересекались задачи с дефолтными стартами

2024-06-20 14:50 UTC, Alex-Ivash commented on src/service/managers/task/InMemoryTaskManager.java
> +        Stream.of(prioritizedTasks.floor(checkedTask), prioritizedTasks.ceiling(checkedTask))
Да, но будет O(n), у меня же O(log n) где-то, из-за поиска пары соседей в красно-черном дереве TreeSet.

Тут просто сравнение пришедшего в аргументе таска с его возможными соседями в приорететном списке. Если мы заранее помещаем в список по приоритетам только таски с заданным временем старта, то разве не рациональнее просто получить возможных соседей таска из сета, до введения этого таска туда и сравнить попарно время старта?

Жертвовать производительностью только ради читабельности мне не кажется хорошей идеей, но могу быть не прав)

2024-06-20 14:53 UTC, Alex-Ivash commented on src/service/managers/task/InMemoryTaskManager.java
> +        validateCollision(newSubtask, oldSubtask);
Там в методе проверка коллизии новой таски с существующими производится, только если были изменения во времени старта или продолжительности по сравнению со старой задачей, которую мы обновляем.
Но выглядит неуместно, согласен - **пофикшу**

2024-06-20 14:58 UTC, Alex-Ivash commented on src/service/managers/task/InMemoryTaskManager.java
> +        List<Subtask> epicsSubtasks = getEpicSubtasks(epic.getId());
Наставник упомянул, что стоит сделать все то в одном цикле, чтобы не делать кучу переборов.
Но вариант с отдельным стримом для расчета каждого отдельного поля - более читаемый, тут не поспоришь, но он менее производительный, опять же.

Мой вариант с расчетом статусов через битовый вектор куда более рациональный, чем прошлый.

2024-06-20 15:20 UTC, Alex-Ivash commented on src/converter/TaskConverter.java
> +        return toString((Task) task).replaceFirst("null", String.valueOf(task.getEpicId()));
Пофиксил

2024-06-20 15:32 UTC, Alex-Ivash commented on src/service/managers/task/InMemoryTaskManager.java
> +    private Task findTask(Task task, int id) {
Пофиксил

2024-06-20 15:40 UTC, Alex-Ivash commented on src/service/managers/task/InMemoryTaskManager.java
> +        historyManager.add(findTask(task, id));
Пофиксил

2024-06-20 15:49 UTC, Alex-Ivash commented on src/model/Task.java
> +    public static final LocalDateTime DEFAULT_START_TIME = LocalDateTime.of(9999, 12, 31, 23, 59, 59);
Перенес константы в менеджер

2024-06-21 05:26 UTC, Alex-Ivash commented on src/service/managers/task/InMemoryTaskManager.java
> +        List<Subtask> epicsSubtasks = getEpicSubtasks(epic.getId());
Порефакторил, упростил, насколько возможно. Сохранил один проход по всем подзадачам

2024-06-21 05:54 UTC, Alex-Ivash commented on src/service/managers/task/InMemoryTaskManager.java
> +        Stream.of(prioritizedTasks.floor(checkedTask), prioritizedTasks.ceiling(checkedTask))
Улучшил читабельность, должно стать понятнее

2024-06-23 21:35 UTC, Alex-Ivash commented on test/service/managers/history/InMemoryHistoryManagerTest.java
> +        IntStream.range(0, taskTypes.size()).forEach(i ->
Пофиксил

2024-06-23 22:18 UTC, Alex-Ivash commented on test/service/managers/history/InMemoryHistoryManagerTest.java
> +        List<Integer> taskIds = taskManager.getAllTasks().stream().map(Task::getId).toList();
Пофиксил

2024-06-23 22:18 UTC, Alex-Ivash commented on test/service/managers/history/InMemoryHistoryManagerTest.java
> +        List<Integer> taskIds = switch (taskType) {
Пофиксил

2024-06-23 22:18 UTC, Alex-Ivash commented on test/service/managers/history/InMemoryHistoryManagerTest.java
> +        int taskId = taskManager.getAllTasks().getFirst().getId();
Пофиксил

2024-06-23 22:23 UTC, Alex-Ivash commented on test/service/managers/history/InMemoryHistoryManagerTest.java
> +    private static ArrayList<Task> testObjectsContainer;
Пификсил

2024-06-23 22:24 UTC, Alex-Ivash commented on test/service/managers/history/InMemoryHistoryManagerTest.java
> +    private static final int TASKS_COUNT = 3;
Пофиксил

2024-06-24 11:35 UTC, Alex-Ivash commented on test/model/EpicTest.java
> +    private static int seq;
Пофиксил

2024-06-24 11:36 UTC, Alex-Ivash commented on test/model/EpicTest.java
> +        testObjectsContainer = new ArrayList<>();
Пофиксил

2024-06-24 11:36 UTC, Alex-Ivash commented on test/model/EpicTest.java
> +            Subtask subtask = new Subtask(++seq, TaskStatus.NEW, "name", "description", epic.getId(), Task.DEFAULT_START_TIME, Task.DEFAULT_DURATION);
Пофиксил

2024-06-24 11:36 UTC, Alex-Ivash commented on test/model/EpicTest.java
> +            testObjectsContainer.add(subtask);
Пофиксил

2024-06-24 11:36 UTC, Alex-Ivash commented on test/model/EpicTest.java
> +        Subtask subtask = new Subtask(++seq, TaskStatus.NEW, "name", "description", epic.getId(), Task.DEFAULT_START_TIME, Task.DEFAULT_DURATION);
Пофиксил

2024-06-24 11:36 UTC, Alex-Ivash commented on test/model/EpicTest.java
Пофиксил

2024-06-24 11:36 UTC, Alex-Ivash commented on test/service/managers/history/InMemoryHistoryManagerTest.java
> +        IntStream.range(0, taskTypes.size()).forEach(i ->
Пофиксил

2024-06-24 11:38 UTC, Alex-Ivash commented on test/service/managers/history/InMemoryHistoryManagerTest.java
Учел, Пофиксил

2024-06-25 08:28 UTC, TomattmanYandex commented on src/converter/TaskConverter.java
> +        LocalDateTime startTime = LocalDateTime.parse(taskFields[6]);
согласен про продолжительность 0 но дефолтное 
но значение старта крайне не логично
и причины на то как минимум две
1) если я вдруг создам что то без времени старта, я не буду понимать почему там какое то  левое значение
2) когда мы устанавливаем одно значение как значение по умолчанию, все таски будут пересекаться по времени

2024-06-25 08:28 UTC, TomattmanYandex commented on src/converter/TaskConverter.java
> +        LocalDateTime startTime = LocalDateTime.parse(taskFields[6]);
не стоит делать что то не логичное ради того чтобы все было без null Значений,
и завязки на какие то константы не привносят читаемости коду

2024-06-25 08:28 UTC, TomattmanYandex commented on src/model/Task.java
> +        this.duration = InMemoryTaskManager.DEFAULT_DURATION;
этим действием ты добавил зависимость таска от таск менеджера, которой раньше не было

2024-06-25 08:28 UTC, TomattmanYandex commented on src/model/Task.java
> +        this.duration = InMemoryTaskManager.DEFAULT_DURATION;
обычно обрабатывают следующим образом
так как ты хочешь сделать чтобы продолжитлеьность и время старта были всегда, то следует убрать конструкторы без этих данных,
 а уже на уровне сервиса, прежде чем сохранять, проверять значение и просетывать дефолттные если там null

2024-06-25 08:28 UTC, TomattmanYandex commented on src/model/TaskStatus.java
> +    NEW(0),
про это будет актуальнее коммент там где оно считается

2024-06-25 08:29 UTC, TomattmanYandex commented on src/model/Task.java
> +    protected TaskStatus status; // TODO сделать статус NEW дефолтным?
ну в принципе логично, но логично делать это в конструкторе

2024-06-25 08:32 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        if (!newTask.getStartTime().equals(Task.DEFAULT_START_TIME)) {
такой прием позволителен, но он реально усложняет понимание кода, появляются какие то волшебные значения
я уже писал, очень часто читаемость и понимаемость кода ставят выше в списке приоритетов

2024-06-25 08:33 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        if (!newTask.getStartTime().equals(Task.DEFAULT_START_TIME)) {
про приоритетный список кстати хорошо, раньше в заданиях так и было, он хранил все, просто наловые значения были в самом конце

2024-06-25 08:38 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
>          Epic subtaskEpic = epics.get(newSubtask.getEpicId());
раньше была проверка на тгдд теперь нету, используй метод getNotNullValue
очень странно когда много логики построено так чтобы не было null значений, но вот в таком очевидном месте забыто

2024-06-25 08:38 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        Epic subtaskEpic = (Epic) findTask(epics.get(newSubtask.getEpicId()), newSubtask.getEpicId());
проверка хорошая и правильная, но я выше или ниже оставлял коментарии по поводу названия этого метода, которое путает, стоит использовать метод getNotNullValue

2024-06-25 08:42 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        Stream.of(prioritizedTasks.floor(checkedTask), prioritizedTasks.ceiling(checkedTask))
жертвовать производительностью ради читаемости не стоит (конечно очень зависит от требований и от масштаба жертв), но тогда текущее решение стоит сделать понятным и читаемым
и сейчас оно гораздо читабельнее

2024-06-25 09:11 UTC, TomattmanYandex approved these changes
Привет, мне очень не нравится зависимость тасков от таск менеджера, я оставил коммент про это где то в ответах на предыдущие комменты
Что касается всего остального, читается намного лучше, все стало гораздо лучше, некоторые моменты все еще считаю что стоит упростить, но это кажется уже вкусовщина

2024-06-25 09:11 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        Task lower = prioritizedTasks.floor(checkedTask);
Всего пара новых переменных, а код уже гораздо лучше читается

2024-06-25 09:11 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +        List<Subtask> epicsSubtasks = getEpicSubtasks(epic.getId());
ну да, тут как всегда упирается в требования и в масштабы, и обычно логика строится от этого,
если планируется что у эпика будут сотни сабтасков, то имлементация будет одна, если планируется что до 10, то тогда перебрать несколько раз не кажется проблемой

2024-06-25 09:11 UTC, TomattmanYandex commented on src/service/managers/task/InMemoryTaskManager.java
> +            statusesBitSet |= 1 << epicSubtask.getStatus().bitSetIndex;
если бы логика была такая, что в итоге мы получаем число соответствующее значению параметра в перечислении, то можно было бы смириться с непонятностью этого фрагмента
но метод getUpdatedEpicStatus(int statusesBitSet) все портит, и сейчас для меня это выглядит как усложненная для понимания версия версия такого кода

TaskStatus status = epicsSubtasks.get(0).getStatus()
for (Subtask epicSubtask : epicsSubtasks) {
  if(status != epicSubtask.getStatus()) {
    status = TaskStatus.IN_PROGRESS;
 }
}
чтобы работало корректно стоит добавить проверку на пустой список

2024-06-25 11:16 UTC, Alex-Ivash commented on src/model/Task.java
> +        this.duration = InMemoryTaskManager.DEFAULT_DURATION;
Я тут понимаю, что они не всегда нужны, ведь есть задачи, которые заводятся просто на будущее без сроков.
Я хотел избавиться от null, потому что посчитал, что так безопаснее и выбрал дату по умолчанию максимально нереальную, как мне показалось.

2024-06-25 11:18 UTC, Alex-Ivash commented on src/service/managers/task/InMemoryTaskManager.java
>          Epic subtaskEpic = epics.get(newSubtask.getEpicId());
Убрал, потому что у нас была установка, что данные будут корректны всегда))
Но это глупо, согласен, пофикшу

2024-06-25 11:40 UTC, Alex-Ivash commented on src/service/managers/task/InMemoryTaskManager.java
> +            statusesBitSet |= 1 << epicSubtask.getStatus().bitSetIndex;
Гениально и просто!
Я не додумался, поправил :)

2024-06-25 17:52 UTC, Alex-Ivash commented on src/model/TaskStatus.java
> +    NEW(0),
Пофиксил

2024-06-25 18:24 UTC, Alex-Ivash commented on src/service/managers/task/InMemoryTaskManager.java
> +        Epic subtaskEpic = (Epic) findTask(epics.get(newSubtask.getEpicId()), newSubtask.getEpicId());
Поправил

2024-06-25 18:57 UTC, Alex-Ivash commented on src/model/Task.java
> +        this.duration = InMemoryTaskManager.DEFAULT_DURATION;
При таком подходе придется делать кучу проверок внутри менеджера в каждом методе на создание и в каждом методе на обновление.

Пока вернул, как было раньше - констатны дефолтного старта и дефолтной продолжительности внутри Task и константа дефолтного окончания в epic, потому что она только там нужна. В след. итерации тогда предлагаю обсудить, чем плох такой подход.

2024-06-25 19:28 UTC, Alex-Ivash commented on src/model/Task.java
> +        this.duration = InMemoryTaskManager.DEFAULT_DURATION;
Исправил

2024-06-25 19:56 UTC, merged